### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by showzyl** [dingyiming/example-vue2#28]
> vue2@ dev /Users/showzyl/Desktop/important/example-vue2
> cross-env NODE_ENV=dev webpack-dev-server --config webpack/dev.js --inline --hot --port 8080

/Users/showzyl/Desktop/important/example-vue2/node_modules/.2.1.0-beta.25@webpack/lib/webpack.js:16
       		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
       		^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output has an unknown property 'publishPath'. These properties are valid:
   object { auxiliaryComment?, chunkFilename?, crossOriginLoading?, devtoolFallbackModuleFilenameTemplate?, devtoolLineToLine?, devtoolModuleFilenameTemplate?, filename?, hashDigest?, hashDigestLength?, hashFunction?, hotUpdateChunkFilename?, hotUpdateFunction?, hotUpdateMainFilename?, jsonpFunction?, library?, libraryTarget?, path?, pathinfo?, publicPath?, sourceMapFilename?, sourcePrefix?, umdNamedDefine? }
   Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
 - configuration.resolve has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
 - configuration.resolve.extensions[0] should not be empty.
 - configuration.resolveLoader has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
    at webpack (/Users/showzyl/Desktop/important/example-vue2/node_modules/.2.1.0-beta.25@webpack/lib/webpack.js:16:9)
    at processOptions (/Users/showzyl/Desktop/important/example-vue2/node_modules/.2.1.0-beta.9@webpack-dev-server/bin/webpack-dev-server.js:294:17)
    at Object.<anonymous> (/Users/showzyl/Desktop/important/example-vue2/node_modules/.2.1.0-beta.9@webpack-dev-server/bin/webpack-dev-server.js:325:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! vue2@ dev: `cross-env NODE_ENV=dev webpack-dev-server --config webpack/dev.js --inline --hot --port 8080`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue2@ dev script 'cross-env NODE_ENV=dev webpack-dev-server --config webpack/dev.js --inline --hot --port 8080'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=dev webpack-dev-server --config webpack/dev.js --inline --hot --port 8080
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/showzyl/Desktop/important/example-vue2/npm-debug.log

**Comment by whatlife** [comment]
@showzyl 来，给你解决方案

执行这个命令，把原来版本卸载了，安装指定的版本。 `2.1.0-beta.21`

> npm uninstall webpack –save-dev 
> npm install webpack@2.1.0-beta.21 –save-dev

**Comment by showzyl** [comment]
@whatlife tkx
